### ISSUE TITLE
/go/pkg/mod/sigs.k8s.io/sig-storage-lib-external-provisioner/v9@v9.0.3/controller/controller.go:868:44: undefined: resourcelock.EndpointsLeasesResourceLock

### ISSUE THREAD

**Issue by adit-cmd** [kubernetes-sigs/sig-storage-lib-external-provisioner#172] opened 2024-05-16 14:59 UTC

**Comment by jsafrane** [comment] 2024-05-23 12:26
Can you please elaborate more on this error? Esp., what go version do you use and what k8s.io/client-go version does your project use? `EndpointsLeasesResourceLock` has been deprecated + removed from client-go a while ago.

sig-storage-lib-external-provisioner v9.0.3 uses k8s.io/client-go v0.26.0 that still has it, I would be very careful upgrading to never client-go releases. Use sig-storage-lib-external-provisioner v10 to get k8s.io/client-go v0.30.0 + lease lock as the default one.

**Comment by Starttoaster** [comment] 2024-06-06 19:04
I also came across this Issue trying to update some dependencies (including client-go.) Thanks for the context, the error makes total sense now. One question I still have is how do I implement leader election in my storage controller code using the latest v10 of this library? I didn't see any mention of leader election in the example, is it handled completely by this library then?

**Comment by thisisharrsh** [comment] 2024-07-11 06:45
Thanks @Starttoaster for sharing the feedback on upgrading to v10 of the library.

**Comment by thisisharrsh** [comment] 2024-07-11 06:52
For others who might be facing the similar issues, i'd like to highlight the some points:

1. when upgrading from the older version to the newer versions, ensure to check the `migration` guides. 
2. as mentioned by @Starttoaster in `v10` the `leader elections` process has been streamlined and includes within the library itself and which simplifying the implementations for the developers.

**Comment by thisisharrsh** [comment] 2024-07-11 06:55
Also @adit-cmd, If the issue is resolved now and you have no other issues to continue with, you can close this issue now.

**Comment by adit-cmd** [comment] 2024-07-11 07:16
Hi All, thanks @Starttoaster  and @thisisharrsh  for the response. I will try to upgrade this library again soon. However as per my experience, im getting stuck in a loop while trying to upgrade this library since the application is dependent on few other modules. Below is the require section.

require (
	github.com/aws/aws-sdk-go v1.25.8
	github.com/aws/aws-sdk-go v1.34.0
	k8s.io/api v0.0.0-20191003000013-35e20aa79eb8
	k8s.io/apimachinery v0.0.0-20190913080033-27d36303b655
	k8s.io/client-go v0.0.0-20191003000419-f68efa97b39e
	k8s.io/klog v1.0.0
	sigs.k8s.io/sig-storage-lib-external-provisioner v4.0.1+incompatible
)

So when I am trying to update the apimachinery and client-go to a later version, I am getting stuck in a loop with the below error while trying to build the docker image:
undefined: resourcelock.EndpointsLeasesResourceLock

Any help is appreciated since I am relatively new to handling go upgrades. Thanks.

**Comment by thisisharrsh** [comment] 2024-07-11 07:31
@adit-cmd, Could you please describe the issue first that you are facing in the [description box](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/172#issue-2300652176), that will be helpful for the other contributors to understand the issue better?

**Comment by thisisharrsh** [comment] 2024-07-15 13:40
> undefined: resourcelock.EndpointsLeasesResourceLock

Since `resourcelock.EndpointsLeasesResourceLock` is no longer available, you'll need to replace it with the newer method of resource locking.

**Closed** 2024-12-12 15:19 UTC
Labels: lifecycle/rotten
