### ISSUE TITLE
Deleting a PVC with a "Terminating" PV does not delete the backing volume

### ISSUE THREAD

**Issue by 27149chen** [kubernetes-sigs/sig-storage-lib-external-provisioner#58] opened 2019-12-20 10:03 UTC
**What happened**:
Deleting a PVC with a "Terminating" PV does not delete the backing volume.

**What you expected to happen**:
The backing volume should be deleted.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a pvc.
2. Wait till pvc and pv are created, and pvc status is "Bound".
3. Delete the pv, the pv will enter "Terminating" status.
4. Delete the pvc.

**Anything else we need to know?**:
After looking into the code, I find `syncVolume` does not delete the volume because `shouldDelete` returns false since the pv's DeletionTimestamp is not nil

**Comment by 27149chen** [comment] 2019-12-23 04:55
@wongma7  @jsafrane  @childsb please have a look.

**Comment by 27149chen** [comment] 2020-01-02 06:20
/ bug

**Comment by jsafrane** [comment] 2020-01-06 09:57
This is basically duplicate of https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/56. Reclaim policy is initiated by PVC deletion. Users should not delete PVs, as it's going to mess up the reclaim policy.

**Comment by 27149chen** [comment] 2020-01-06 11:27
Yes, both cases point to "shouldDelete", but I don't think it is duplicate. Users should not delete PVs, but what if it is a mistake? k8s has a mechanism to prevent it from being deleted by mistake, also, I think k8s should ensure when such a mistake happen, user is able to clean up this pv and its backing volume.
what do you think?

**Comment by wongma7** [comment] 2020-01-06 19:17
Would rather leak a backing volume than delete it and risk unintentional data loss. It's probably dangerous to change this behavior at this point. Generally users should not be given write access to PVs in the first place so I don't think it is worth the risk to make such a change.

**Closed** 2020-06-04 21:07 UTC
Labels: lifecycle/rotten
